// icons
import { FaChartBar } from "react-icons/fa6";
// Components
import AnalitikaView from "../pages/AnalitikaPage";

// const sidebar = [
//   {
//     id: 1,
//     title: "Analitika",
//     path: "/analitka",
//     icon: FaChartBar,
//     isPrivate: true,
//     element: AnalitikaView,
//     role: ["admin", "manager"],
//   },
//   {
//     id: 2,
//     title: "Lidlar", // buyurtma
//     path: "/lidlar",
//     isPrivate: true,
//     icon: FaChartBar,
//     element: AnalitikaView,
//     role: ["admin"],
//     children: [
//       {
//         id: `2-1`,
//         parentID: 2,
//         title: "Barcha Lidlar",
//         path: "/lidlar/all-lids",
//         isPrivate: true,
//         element: AnalitikaView,
//         role: ["admin", "manager"],
//       },
//     ],
//   },
// ];
const sidebar = [
  {
    id: 1,
    title: "Analitka",
    path: "/analitka",
    icon: FaChartBar,
    isPrivate: true,
    element: AnalitikaView,
    role: ["admin"],
  },
  {
    id: 2,
    title: "Home",
    path: "/home",
    icon: FaChartBar,
    isPrivate: true,
    element: AnalitikaView,
    role: ["admin"],
    children: [
      {
        id: `2-1`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-2`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-3`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-1`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-2`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-3`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
    ]
  },
  {
    id: 3,
    title: "Hello",
    path: "/hello",
    icon: FaChartBar,
    isPrivate: true,
    element: AnalitikaView,
    role: ["admin"],
  },
  {
    id: 4,
    title: "Home",
    path: "/home",
    icon: FaChartBar,
    isPrivate: true,
    element: AnalitikaView,
    role: ["admin"],
    children: [
      {
        id: `4-1`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `4-2`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `4-3`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `4-4`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `4-5`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-1`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-2`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-3`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-1`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-2`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
      {
        id: `2-3`,
        title: "Ochiq ma'lumotlar",
        path: "/home/ochiq-malumotlar",
        isPrivate: true,
        element: AnalitikaView,
        role: ["admin"],
      },
    ]
  },
]

export default sidebar;
